name: ssh_yonetim
description: "RoPi SSH Manager Pro - Cross-platform SSH Client and Server Manager by RoPi LLC."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  dartssh2: ^2.15.0
  xterm: ^4.0.0
  sqflite_common_ffi: ^2.3.4
  sqlite3_flutter_libs: ^0.5.28
  encrypt: ^5.0.3
  crypto: ^3.0.5
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.5
  path: ^1.9.0
  file_picker: ^8.1.7
  window_manager: ^0.4.3
  google_fonts: ^6.2.1
  intl: ^0.20.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
dependency_overrides:
  # pointycastle'ı dartssh2'nin istediği 4.x sürümüne zorluyoruz
  # (encrypt paketi API düzeyinde pointycastle 4 ile genelde sorunsuz çalışır)
  pointycastle: ^4.0.0